### ISSUE TITLE
Clarification on browser requirements

### ISSUE THREAD

**Issue by leemason** [vuejs/vue-web-component-wrapper#5]
First off thanks for the great work on vuejs and this library looks like a really good next step.

Im a little confused by the requirements regarding es2015 classes. Can we not transpile the code with buble or bable?

Is the reason for class requirements to do with the customElement api and how is this effected by the polyfill available here: https://github.com/WebReflection/document-register-element.
Should we include the polyfill?

**Comment by yyx990803** [comment]
Transpiled classes have issues because without native class support a ES5 constructor cannot properly extend the built-in `HTMLElement`. This is why there needs to be a [hacky adaptor](https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs) for it.

Either way, based on the fact that:

- All browsers that natively support Custom Elements also support ES classes;
- If a browser does not support ES classes it definitely does not support native Custom Elements.

In the latter case, you will need load all the polyfills for marginal benefits, while introducing degraded performance and compatibility complexities into your setup. This in my opinion using Web Components in older browsers really is using a technology for the sake of using it and not worth pursuing at all.
